- name: composer
  src: geerlingguy.composer
  version: 1.9.0

- name: ntp
  src: geerlingguy.ntp
  version: 2.2.0

- name: logrotate
  src: nickhammond.logrotate
  version: v0.0.5

- name: swapfile
  src: oefenweb.swapfile
  version: v2.0.26

- name: mailhog
  src: geerlingguy.mailhog
  version: 2.2.0

- name: nodejs
  src: geerlingguy.nodejs
  version: 5.1.1